export const options = [
  { label: 'ධර්ම දාන', value: 'dharma_dana' },
  { label: 'සාංඝික දාන', value: 'sanghika_dana' },
  { label: 'භාණ්ඩ/උපකරණ පූජා ', value: 'upakarana_puja' },
  { label: 'විහාර කර්මාන්ත', value: 'vihara_karmanta' },
  { label: 'ආලෝක පූජා', value: 'aloka_pooja' },
  { label: 'අභය දාන ', value: 'abahay_dana' },
  { label: 'වස්සාන කාල සහ කඨිණ පින්කම්', value: 'kathina' },
  { label: 'තෙරුවන්ට පූජා', value: 'theruwanta_pooja' },
  { label: 'ස්වර්ණමාලී මහා සෑය', value: 'swarnamali_maha_seya' },
  { label: 'පිරිකර පූජා', value: 'pirikara_pooja' },
  { label: 'ශිලා සමාදාන', value: 'shila_samadana' },
  { label: 'වන්දනා ගමන්', value: 'vandana_gaman' },
  { label: 'අධ්‍යාපන', value: 'adhyaapana' },
  { label: 'තිරිසන් සතුන් සම්බන්ධ', value: 'thirisan_sathun_sambanda' },
  { label: 'සෞඛ්‍ය සම්බන්ධ', value: 'saukhya_sambandha' },
  { label: 'විවිධ', value: 'vividha' },
];
